eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765
spring:
  application:
    name: service-feign

feign:
  hystrix:
    enabled: true

#localhost添加进proxy-stream-allow-list数组当中，防止无法访问
hystrix:
  dashboard:
    proxy-stream-allow-list: "localhost"
