eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765
spring:
  application:
      name: service-feign
  sleuth:
    #设置web开启sleuth功能
    web:
      client:
        enabled: true
    #设置为1.0时就是链路数据100%收集到zipkin-server;设置为0.1时，即10%概率收集链路数据
    sampler:
      probability: 1.0 # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1

feign:
  hystrix:
    enabled: true

#localhost添加进proxy-stream-allow-list数组当中，防止无法访问
hystrix:
  dashboard:
    proxy-stream-allow-list: "localhost"
