server:
  port: 8762

spring:
  application:
    name: eureka-client
  #指定zipkin server的地址
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      #高可用的服务注册中心（F版本）
      #defaultZone: http://peer1:8770/eureka/,http://peer2:8771/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"



