server:
  port: 8762

spring:
  application:
    name: eureka-client
  sleuth:
    #设置web开启sleuth功能
    web:
      client:
        enabled: true
    #设置为1.0时就是链路数据100%收集到zipkin-server;设置为0.1时，即10%概率收集链路数据
    sampler:
      probability: 1.0 # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
  #指定zipkin server的地址
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      #高可用的服务注册中心（F版本）
      #defaultZone: http://peer1:8770/eureka/,http://peer2:8771/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"



