server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    #registerWithEureka=false,fetchRegistry: false 表明 这是一个eureka server
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: eureka-server
